### ISSUE TITLE
No shadow on left menu

### ISSUE THREAD

**Issue by arx-it** [Baseflow/Xamarin-Sidebar#27]
When I set the menu on the left, there's no shadow.

Anyone ever tried this?

**Comment by johnnysbug** [comment]
I don't see a shadow on a left menu, nor does it hide the status bar. Here's my code to set it up:

```
var root = UIApplication.SharedApplication.KeyWindow.RootViewController;

SidebarController = new SidebarController(root, this, new MenuViewController());
SidebarController.HasShadowing = true;
SidebarController.StatusBarMoves = true;
SidebarController.MenuLocation = SidebarController.MenuLocations.Left;

this.MenuButton.TouchUpInside += (sender, e) => { SidebarController.ToggleMenu(); };
```

In this code, `this` is a UITabBarController.

I am using version 1.8.

**Comment by johnnysbug** [comment]
I figured this out. If the menu is going to be on the left side, the SidbarController needs to set the ShadowOffset to `new SizeF(0, 0)` instead of `new SizeF(5, 0)`.

If my thinking is correct, the shadow is there, but it is offset 5 points under the content view.

I'll make a PR for this in a few minutes.

**Comment by jdehlin** [comment]
Thanks for reporting this issue and for the pull request!
