### ISSUE TITLE
Swipe Gesture BUG

### ISSUE THREAD

**Issue by jposes22** [Baseflow/Xamarin-Sidebar#48]
I use the menú and works perfectly but if i try add gesture swipe in a subview in the center ViewController (contentAreaController) this gesture doesn´t work, but if I create a view controller without this menu works correctly.

**Comment by conrad90909** [comment]
+1 for this, trying to implement a swipe to delete feature on a UITableView and the menu control is blocking the swipe, will only come up with delete option 1 in every 20 or so swipes, is there any way around this yet? Many thanks!

**Comment by jdehlin** [comment]
I'll try to look into this issue this week.

**Comment by conrad90909** [comment]
@jdehlin - Hi Jack, did you manage to look into this yet?

Many thanks.

Conrad

**Comment by jdehlin** [comment]
Sorry for the delay. Looked at it for a bit and no simple solution popped out. Investigating it some more.

**Comment by kinex** [comment]
I had similar issue with my UITableView (a feature for reordering UITableView rows stopped working). My workaround is to disable SidebarController temporarily in this specific subview (property SidebarController.Disabled). This works fine in my case, because in my design the menu should be available only from the app home page anyway. I guess the issue must be related to a gesture recognizer allowing to drag the menu in view from the edge of the screen. It would be nice to have a property for disabling this feature. In my app I prefer having only a button for showing/hiding the menu. It is also quite alarming if the feature has this kind of side effects to the actual app.

**Comment by jdehlin** [comment]
Closing as resolved by #60
